/**********************************************************************************************************************
 * \file AudioModule.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "IfxAsclin_Asc.h"
#include "IfxAsclin_PinMap.h"
#include "IfxCpu_Irq.h"
#include "IfxStm.h"
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define ASC_TX_BUF_SIZE (64)
#define ASC_RX_BUF_SIZE (64)

#define AUDIO_MODULE_BAUD_RATE  (9600)
#define AUDIO_MODULE_MAX_VOLUME (30U)

#define INTPRIO_ASCLIN_TX  (1)
#define INTPRIO_ASCLIN_RX  (2)

IFX_INTERRUPT(asclinTxISR, 0, INTPRIO_ASCLIN_TX);
IFX_INTERRUPT(asclinRxISR, 0, INTPRIO_ASCLIN_RX);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

uint8 ascTxBuf[ASC_TX_BUF_SIZE + sizeof(Ifx_Fifo) + 8];
uint8 ascRxBuf[ASC_RX_BUF_SIZE + sizeof(Ifx_Fifo) + 8];

IfxAsclin_Asc audioModuleHandle;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/* UART 통신용 ISR */
void asclinTxISR(void);
void asclinRxISR(void);

void initAudioModule(IfxAsclin_Tx_Out* pTxPort, IfxAsclin_Rx_In* pRxPort, void* pAsclinModule);
void resetAudioModule(void);

void sendAudioModulePacket(uint8 cmd, uint8 paramHigh, uint8 paramLow);

void setAudioModuleVolume(uint8 volume);
void playTrack(uint8 track);

/* 오디오 모듈 알림 재생 함수들 */
void playDoorOpenSound(void);
void playDoorCloseSound(void);
void playSlopeOpenSound(void);
void playSlopeCloseSound(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void asclinTxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&audioModuleHandle);
}

void asclinRxISR(void)
{
    IfxAsclin_Asc_isrReceive(&audioModuleHandle);
}

void initAudioModule(IfxAsclin_Tx_Out* pTxPort, IfxAsclin_Rx_In* pRxPort, void* pAsclinModule)
{
    IfxAsclin_Asc_Config ascConfig;

    IfxAsclin_Asc_initModuleConfig(&ascConfig, pAsclinModule);

    //ascConfig.clockSource = IfxAsclin_ClockSource_kernelClock;
    ascConfig.baudrate.baudrate = AUDIO_MODULE_BAUD_RATE;
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN_RX;
    ascConfig.interrupt.typeOfService = 0;

    // 핀 설정
    const IfxAsclin_Asc_Pins pins = {
            NULL_PTR,   IfxPort_InputMode_pullUp,
            pRxPort,    IfxPort_InputMode_pullUp,
            pTxPort,    IfxPort_OutputMode_pushPull,
            NULL_PTR,   IfxPort_OutputMode_pushPull,
            IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    // 버퍼 설정
    ascConfig.txBuffer = ascTxBuf;
    ascConfig.txBufferSize = ASC_TX_BUF_SIZE;
    ascConfig.rxBuffer = ascRxBuf;
    ascConfig.rxBufferSize = ASC_RX_BUF_SIZE;

    // 모듈 초기화
    IfxAsclin_Asc_initModule(&audioModuleHandle, &ascConfig);
}

void sendAudioModulePacket(uint8 cmd, uint8 paramHigh, uint8 paramLow)
{
    uint8 packet[10] = { 0x7E, 0xFF, 0x06, cmd, 0x00, paramHigh, paramLow, 0x00, 0x00, 0xEF };

    uint16 checksum = 0xFFFF - (packet[1] + packet[2] + packet[3] + packet[4] + packet[5] + packet[6]) + 0x1;
    packet[7] = (uint8)(checksum >> 8);
    packet[8] = (uint8)(checksum & 0x00FF);

    // Asc드라이버 전송 로직
    Ifx_SizeT count = 10;
    IfxAsclin_Asc_write(&audioModuleHandle, packet, &count, TIME_INFINITE);
}

void resetAudioModule(void)
{
    sendAudioModulePacket(0x0C, 0x00, 0x00);
}

void setAudioModuleVolume(uint8 volume)
{
    uint8 value = (volume < AUDIO_MODULE_MAX_VOLUME) ? volume : AUDIO_MODULE_MAX_VOLUME;
    sendAudioModulePacket(0x06, 0x00, value);
}

void playTrack(uint8 track)
{
    sendAudioModulePacket(0x0F, 0x1, track);
}

void playDoorOpenSound(void)
{
    playTrack(1);
}

void playDoorCloseSound(void)
{
    playTrack(2);
}

void playSlopeOpenSound(void)
{
    playTrack(3);
}

void playSlopeCloseSound(void)
{
    playTrack(4);
}
