/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "monitor_module.h"
#include "IfxStm.h"

extern IfxCpu_syncEvent cpuSyncEvent;

void core1_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG1 IS DISABLED HERE!! */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);
    
    initMonitor(&IfxI2c0_SCL_P13_1_INOUT, &IfxI2c0_SDA_P13_2_INOUT, &MODULE_I2C0);

    // 1. 초기화 및 기준 시간 설정
    uint32 ticksFor1Sec = IfxStm_getTicksFromMilliseconds(&MODULE_STM1, 100);
    uint32 lastTick = IfxStm_get(&MODULE_STM1); // 마지막으로 출력한 시점 기록

    printMonitor();

    while(1)
    {
        // 2. 현재 시간(Tick) 가져오기
        uint32 currentTick = IfxStm_get(&MODULE_STM1);

        // 3. (현재 시간 - 마지막 기록 시간)이 1초(ticksFor1Sec)보다 큰지 확인
        if (currentTick - lastTick >= ticksFor1Sec)
        {
            refreshMonitor();

            // 4. 기준 시간을 현재 시간으로 업데이트 (또는 lastTick += ticksFor1Sec)
            lastTick = currentTick;
        }

        /* * 여기서 멈추지 않고 다른 작업을 수행할 수 있습니다.
         * 예를 들어 센서 값을 읽거나 통신 상태를 체크하는 등의 작업을
         * 1초 대기 시간 도중에 계속 처리할 수 있습니다.
         */
    }
}
