/**********************************************************************************************************************
 * \file fire_detect_module.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Ifx_Types.h"
#include "IfxStm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define FIRE_THRESHOLD  (1.2f)

#define STM_MODULE      (&MODULE_STM0)


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

volatile uint8 gTemp = 0;
volatile uint8 gHumi = 0;

volatile uint8 gTempList[10] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
volatile uint8 gTempNum = 0;

volatile boolean gIsFireDetected = FALSE;

Ifx_P* gDHT11_PIN_GROUP = NULL;
uint32 gDHT11_PIN       = 0;

volatile sint32 gFireDetectModuleState = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

static void delayUs(uint32 us);
static void delayMs(uint32 ms);

static boolean isDHTHigh(void);

static boolean waitUntilLevel(boolean targetLevel, uint32 timeoutUs);

static sint32 readDHT11(void);

void initFireDetectModule(Ifx_P* pPortGroup, uint32 portNum);
void updateFireDetectModule(void);
boolean isFireDetected(void);


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

static void delayUs(uint32 us)
{
    Ifx_TickTime ticks = IfxStm_getTicksFromMicroseconds(STM_MODULE, us);
    IfxStm_waitTicks(STM_MODULE, ticks);
}

static void delayMs(uint32 ms)
{
    Ifx_TickTime ticks = IfxStm_getTicksFromMilliseconds(STM_MODULE, ms);
    IfxStm_waitTicks(STM_MODULE, ticks);
}

static boolean isDHTHigh(void)
{
    boolean value = (IfxPort_getPinState(gDHT11_PIN_GROUP, gDHT11_PIN) != 0);

    return value;
}

static boolean waitUntilLevel(boolean targetLevel, uint32 timeoutUs)
{
    uint32 start = STM_MODULE->TIM0.U;
    uint32 timeoutTicks = (uint32)IfxStm_getTicksFromMicroseconds(STM_MODULE, timeoutUs);

    /* DHT에서 보내오는 디지털 신호가 targetLevel이 될 때까지 Blocking */
    while(isDHTHigh() != targetLevel) {
        if((uint32)(STM_MODULE->TIM0.U - start) > timeoutTicks)
        {
            return FALSE;
        }
    }

    return TRUE;
}

static sint32 readDHT11()
{
    /* 통신 초기화 */
    IfxPort_setPinMode(gDHT11_PIN_GROUP, gDHT11_PIN, IfxPort_Mode_outputOpenDrainGeneral);
    IfxPort_setPinState(gDHT11_PIN_GROUP, gDHT11_PIN, IfxPort_State_high);
    delayMs(1);  // Blocking

    IfxPort_setPinState(gDHT11_PIN_GROUP, gDHT11_PIN, IfxPort_State_low);
    delayMs(20);

    IfxPort_setPinState(gDHT11_PIN_GROUP, gDHT11_PIN, IfxPort_State_high);
    delayUs(30);

    /* 센서 값 읽어오기 */
    IfxPort_setPinMode(gDHT11_PIN_GROUP, gDHT11_PIN, IfxPort_Mode_inputPullUp);

    // 인터럽트 차단
    boolean intState = IfxCpu_disableInterrupts();

    if(!waitUntilLevel(FALSE, 200)) { IfxCpu_restoreInterrupts(intState); return -1; }
    if(!waitUntilLevel(TRUE, 200))  { IfxCpu_restoreInterrupts(intState); return -2; }
    if(!waitUntilLevel(FALSE, 200)) { IfxCpu_restoreInterrupts(intState); return -3; }

    /* 5bytes 읽어오기 */
    uint8 data[5] = { 0, 0, 0, 0, 0 };

    uint32 thresholdTicks = (uint32)IfxStm_getTicksFromMicroseconds(&MODULE_STM0, 40);

    for(int i = 0; i < 5; i++)
    {
        for(int j = 0; j < 8; j++)
        {
            if(!waitUntilLevel(TRUE, 100)) { IfxCpu_restoreInterrupts(intState); return -10; }

            uint32 startTicks = MODULE_STM0.TIM0.U; // HIGH 시작 시간 기록

            if(!waitUntilLevel(FALSE, 100)) { IfxCpu_restoreInterrupts(intState); return -11; }

            uint32 durationTicks = (uint32)(MODULE_STM0.TIM0.U - startTicks); // 유지된 총 시간 계산

            data[i] <<= 1;

            // 유지된 시간이 40us보다 길면 '1', 짧으면 '0'
            if(durationTicks > thresholdTicks)
            {
                data[i] |= 1;
            }
        }
    }

    // 인터럽트 복구
    IfxCpu_restoreInterrupts(intState);

    /* checksum 확인 */
    uint8 sum = data[0] + data[1] + data[2] + data[3];
    if(sum != data[4]) return -20;

    gTemp = data[2];
    gHumi = data[0];

    gTempList[gTempNum++] = gTemp;
    if(gTempNum > 9) {
        gTempNum = 0;
    }

    return 1;
}

void initFireDetectModule(Ifx_P* pPortGroup, uint32 portNum)
{
    gDHT11_PIN_GROUP = pPortGroup;
    gDHT11_PIN = portNum;

    // idle 상태로 먼저 놓기
    IfxPort_setPinMode(gDHT11_PIN_GROUP, gDHT11_PIN, IfxPort_Mode_inputPullUp);

    // 전원 안정화 대기
    delayMs(1500);
}


void updateFireDetectModule(void)
{
    gFireDetectModuleState = readDHT11();

    if((float)((float)gTempList[9] / (float)gTempList[5]) > FIRE_THRESHOLD) {
        gIsFireDetected = TRUE;
    }

    delayMs(2000);
}

boolean isFireDetected(void) {
    return gIsFireDetected;
}
