/**********************************************************************************************************************
 * \file monitor_module.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "IfxI2c_I2c.h"
#include "IfxStm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define LCD_I2C_ADDR    ((0x27 << 1) & 0xFE)
#define LCD_BAUD_RATE   (100000)
#define LCD_BACKLIGHT   (0x08)
#define LCD_ENABLE      (0x04)
#define LCD_RS          (0x01)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

volatile uint8 monitorFlags;

static IfxI2c_I2c I2CModuleHandle;
static IfxI2c_I2c_Device monitorModuleHandle;

static uint8 customChar0[8] = {
        0x00, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x00
};  // On 아이콘

static uint8 customChar1[8] = {
        0x00, 0x1F, 0x11, 0x11, 0x11, 0x11, 0x1F, 0x00
};  // Off 아이콘

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

void delayMs(uint8 ms);

void initMonitor(IfxI2c_Scl_InOut* pSCLPort, IfxI2c_Sda_InOut* pSDAPort, void* pI2CModule);
void writeBytes(const uint8* pData, Ifx_SizeT size);
void writeBytesToExpander(uint8 data);
void writeNibbleWithCtrlToLCD(uint8 dataWithCtrl);
void sendByteToLCD(uint8 data, uint8 mode);
void sendCmdToLCD(uint8 cmd);
void sendDataToLCD(uint8 data);
void createCustomChar(uint8 idx, const uint8 pattern[8]);
void loadCustomChars(void);

void clearMonitor(void);
void setLCDCursor(uint8 row, uint8 col);
void printLCDString(const char* str);
void printLCDCustomChar(uint8 idx);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void delayMs(uint8 ms)
{
    Ifx_TickTime ticks = IfxStm_getTicksFromMilliseconds(&MODULE_STM0, ms);
    IfxStm_waitTicks(&MODULE_STM0, ticks);
}

void initMonitor(IfxI2c_Scl_InOut* pSCLPort, IfxI2c_Sda_InOut* pSDAPort, void* pI2CModule)
{
    // I2C Init
    IfxI2c_I2c_Config I2CConfig;
    IfxI2c_I2c_initConfig(&I2CConfig, pI2CModule);

    const IfxI2c_Pins pins = {
            pSCLPort,
            pSDAPort,
            IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    I2CConfig.pins = &pins;

    I2CConfig.baudrate = LCD_BAUD_RATE;
    IfxI2c_I2c_initModule(&I2CModuleHandle, &I2CConfig);

    IfxI2c_I2c_deviceConfig deviceConfig;
    IfxI2c_I2c_initDeviceConfig(&deviceConfig, &I2CModuleHandle);

    deviceConfig.deviceAddress = LCD_I2C_ADDR;
    IfxI2c_I2c_initDevice(&monitorModuleHandle, &deviceConfig);

    // LCD Init
    delayMs(50);  // 전원 안정화 대기

    for(uint8 i = 0; i < 3; i++) {
        // 4비트 제어 모드로 변경전 8비트 모드로 강제 변경(제어 일관성을 위해)
        writeNibbleWithCtrlToLCD(0x30);
        delayMs(5);
    }

    // 4비트 제어 모드로 강제 변경
    writeNibbleWithCtrlToLCD(0x20);
    delayMs(2);

    sendCmdToLCD(0x28);  // 4비트 모드, 2줄, 5x8 폰트
    sendCmdToLCD(0x0C);  // 화면 키기, 커서 숨김, 깜빡임 없음
    sendCmdToLCD(0x06);  // 글자 쓰면 자동으로 커서 오른쪽으로 이동
    sendCmdToLCD(0x01);  // 화면 초기화 글자 모두 지우기
    delayMs(2);

    // CustomChar 등록
    loadCustomChars();
    clearMonitor();
}

void writeBytes(const uint8* pData, Ifx_SizeT size)
{
    IfxI2c_I2c_write(&monitorModuleHandle, (uint8*)pData, size);
}

void writeBytesToExpander(uint8 data)
{
    uint8 txByte = data | LCD_BACKLIGHT;
    writeBytes(&txByte, 1);
}

void enableLCD(uint8 data)
{
    writeBytesToExpander(data | LCD_ENABLE);
    delayMs(1);
    writeBytesToExpander(data & (uint8)(~LCD_ENABLE));
    delayMs(1);
}

void writeNibbleWithCtrlToLCD(uint8 nibbleWithCtrl)
{
    writeBytesToExpander(nibbleWithCtrl);
    enableLCD(nibbleWithCtrl);
}

void sendByteToLCD(uint8 data, uint8 mode)
{
    uint8 nibbleHigh = (data & 0xF0) | mode;
    uint8 nibbleLow = ((data << 4) & 0xF0) | mode;

    writeNibbleWithCtrlToLCD(nibbleHigh);
    writeNibbleWithCtrlToLCD(nibbleLow);
}

void sendCmdToLCD(uint8 cmd)
{
    sendByteToLCD(cmd, 0x00);
}

void sendDataToLCD(uint8 data)
{
    sendByteToLCD(data, LCD_RS);
}

void createCustomChar(uint8 idx, const uint8 pattern[8])
{
   idx &= 0x07;

   sendCmdToLCD(0x40 | (idx << 3));

   for(uint8 i = 0; i < 8; i++) {
       sendDataToLCD(pattern[i]);
   }

   delayMs(2);
}

void loadCustomChars(void)
{
    createCustomChar(0, customChar0);
    createCustomChar(1, customChar1);
}

void clearMonitor(void)
{
    sendCmdToLCD(0x01);
    delayMs(1);
}

void setLCDCursor(uint8 row, uint8 col)
{
    uint8 rowAddr[2] = { 0x00, 0x40 };
    sendCmdToLCD(0x80 | (rowAddr[row] + col));
}

void printLCDString(const char* str)
{
    while(*str != '\0')
    {
        sendDataToLCD((uint8)(*(str++)));
    }
}

void printLCDCustomChar(uint8 idx) {
    sendDataToLCD(idx & 0x07);
}

void printMonitor() {
    boolean isDoorOpened = monitorFlags & 0x80;
    boolean isSlopeOpened = monitorFlags & 0x40;
    boolean isBlocked = monitorFlags & 0x20;
    boolean isStopBellPressed = monitorFlags & 0x10;

    /* 항목명 출력 */
    setLCDCursor(0, 0);
    printLCDString("Door   ");
    setLCDCursor(0, 9);
    printLCDString("Slope ");
    setLCDCursor(1, 0);
    printLCDString("Block ");
    setLCDCursor(1, 9);
    printLCDString("Stop  ");

    /* 상태 출력 */
    setLCDCursor(0, 7);
    printLCDCustomChar((isDoorOpened) ? 0 : 1);
    setLCDCursor(0, 15);
    printLCDCustomChar((isSlopeOpened) ? 0 : 1);
    setLCDCursor(1, 7);
    printLCDCustomChar((isBlocked) ? 0 : 1);
    setLCDCursor(1, 15);
    printLCDCustomChar((isStopBellPressed) ? 0 : 1);
}

void refreshMonitor() {
    //clearMonitor();
    //delayMs(1);
    printMonitor();
}
