#ifndef CAN_TEST_SELECTOR_H
#define CAN_TEST_SELECTOR_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum CANTestIdEnum
{
    CAN_TEST_NONE = 0,

    CAN_TEST_CORE_TIMEOUT_SEND_SUCCESS,
    CAN_TEST_CORE_TIMEOUT_SEND_EXPIRED,
    CAN_TEST_CORE_TIMEOUT_RECEIVE_SUCCESS,
    CAN_TEST_CORE_TIMEOUT_RECEIVE_EXPIRED,

    CAN_TEST_LOOPBACK_CLASSIC_FIFO0_ACCEPT_ALL,
    CAN_TEST_LOOPBACK_CLASSIC_BUFFER_EXACT,
    CAN_TEST_LOOPBACK_FD_64_NO_BRS,
    CAN_TEST_LOOPBACK_FD_64_BRS,

    CAN_TEST_EXT_CLASSIC_BUFFER_EXACT,
    CAN_TEST_EXT_FD_BRS_BUFFER_EXACT,
    CAN_TEST_EXT_CLASSIC_FIFO0_ACCEPT_ALL,
    CAN_TEST_EXT_FD_BRS_FIFO0_ACCEPT_ALL,

    CAN_TEST_TIMEOUT_ITG_SEND_IMMEDIATE,
    CAN_TEST_TIMEOUT_ITG_RECEIVE_EXPIRED,

    CAN_TEST_CORE_LIFECYCLE_MATRIX,
    CAN_TEST_CORE_INVALID_BINDING,
    CAN_TEST_TC3XX_PLATFORM_NEGATIVE,
    CAN_TEST_TC3XX_OPEN_CONFIG_NEGATIVE,

    CAN_TEST_REAL_PORT_SMOKE,
    CAN_TEST_REAL_PORT_EXECUTOR_SMOKE,
    CAN_TEST_REAL_PORT_CONTEXT_SMOKE,
    CAN_TEST_REAL_PORT_CONTEXT_HELPERS_SMOKE,
    CAN_TEST_REAL_PORT_ERROR_RECOVER_SMOKE,
    CAN_TEST_REAL_PORT_SERVICE_SMOKE,
    CAN_TEST_REAL_PORT_SOCKET_SMOKE,

    CAN_TEST_CORE_OPTIONAL_OPS,
    CAN_TEST_CORE_POLL,
    
    CAN_TEST_CORE_OPERATION,
    CAN_TEST_CORE_EXECUTOR,
    CAN_TEST_CORE_EXECUTOR_DRAIN,
    CAN_TEST_CORE_EXECUTOR_ALIAS,
    CAN_TEST_CORE_CONTEXT,
    CAN_TEST_CORE_CONTEXT_HELPERS,
    CAN_TEST_CORE_SERVICE,
    CAN_TEST_CORE_SOCKET,
    CAN_TEST_CORE_SOCKET_SUGAR
} CANTestId;

typedef enum CANTestCategoryEnum
{
    CAN_TEST_CATEGORY_NONE = 0,
    CAN_TEST_CATEGORY_CORE_UNIT,
    CAN_TEST_CATEGORY_CORE_INTEGRATION,
    CAN_TEST_CATEGORY_TC3XX_NEGATIVE,
    CAN_TEST_CATEGORY_REAL_PORT
} CANTestCategory;

typedef struct CANTestRunResultStruct
{
    CANTestId id;
    const char *name;
    CANTestCategory category;
    bool executed;
    bool passed;
} CANTestRunResult;

const char *CANTestSelectorGetName(CANTestId id);
CANTestCategory CANTestSelectorGetCategory(CANTestId id);

bool CANTestSelectorRun(CANTestId id, CANTestRunResult *result);

#ifdef __cplusplus
}
#endif

#endif